name: Pivotal Campaign Services
favicon: null
layout_spectrum: 0.34699629549868405
typography_spectrum: 0.6927530900575221
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73330125-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6996464719995856
  lightness: 0.8244350461754948
  saturation: 0.0478282873518765
  rhythmicContrast: 0.06382844550535083
purpose: []
